replicaCount: 1

image:
  repository: registry.gitlab.com/villageaccounting/villageaccapi
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets : [gitlab-secert]
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.hometsd.me
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - api.hometsd.me
      secretName: api.hometsd-me-tls
vault:
  enabled: true
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "dockerhub-policy"  # ระบุ role ที่ใช้ใน Vault
    vault.hashicorp.com/agent-inject-secret-docker-config: "gitlab/pull"
    vault.hashicorp.com/agent-inject-template-docker-config: |
      {
        "auths": {
          "registry.gitlab.com": {
            "username": "{{ .Data.gitlab_username }}",
            "password": "{{ .Data.gitlab_password }}"
          }
        }
      }