replicaCount: 1

image:
  repository: registry.gitlab.com/villageaccounting/villageaccapi
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: gitlab-secret

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.hometsd.me
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - api.hometsd.me
      secretName: api.hometsd-me-tls

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-secret-gitlab-secret: "gitlab/pull"
  vault.hashicorp.com/agent-inject-template-gitlab-secret: |
    {{- with secret "gitlab/pull" -}}
    - name: gitlab-secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: {{ .Data.data | base64encode }}
    {{- end }}
