# replicaCount: 1

# image:
#   repository: registry.gitlab.com/villageaccounting/villageaccapi
#   pullPolicy: IfNotPresent
#   tag: "latest"

# imagePullSecrets : [gitlab-secert]
# service:
#   type: ClusterIP
#   port: 80

# ingress:
#   enabled: true
#   className: "nginx"
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     cert-manager.io/cluster-issuer: "letsencrypt-prod"
#   hosts:
#     - host: api.hometsd.me
#       paths:
#         - path: /
#           pathType: ImplementationSpecific
#   tls:
#     - hosts:
#         - api.hometsd.me
#       secretName: api.hometsd-me-tls

replicaCount: 1

image:
  repository: registry.gitlab.com/villageaccounting/villageaccapi
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.hometsd.me
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - api.hometsd.me
      secretName: api.hometsd-me-tls

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-secret-imagepull: "gitlab/pull"
  vault.hashicorp.com/agent-inject-template-imagepull: |
    {{- with secret "gitlab/pull" -}}
    {
      "auths": {
        "registry.gitlab.com": {
          "username": "{{ .Data.username }}",
          "password": "{{ .Data.password }}",
          "auth": "{{ printf "%s:%s" .Data.username .Data.password | base64 }}"
        }
      }
    }
    {{- end }}