replicaCount: 1

image:
  repository: registry.gitlab.com/villageaccounting/villageaccapi
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets : [gitlab-secert]
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.hometsd.me
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - api.hometsd.me
      secretName: api.hometsd-me-tls