apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "argocd-web.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host }}
      http:
        paths:
          - path: {{ (index (index .Values.ingress.hosts 0).paths 0).path }}
            pathType: {{ (index (index .Values.ingress.hosts 0).paths 0).pathType }}
            backend:
              service:
                name: {argocd-server}
                port:
                  number: {443}
  tls:
    - hosts:
        - {{ (index .Values.ingress.hosts 0).host }}
      secretName: {{ (index .Values.ingress.tls 0).secretName }}