apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "accvillage-web.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host }}
      http:
        paths:
          - path: {{ (index (index .Values.ingress.hosts 0).paths 0).path }}
            pathType: {{ (index (index .Values.ingress.hosts 0).paths 0).pathType }}
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
  tls:
    - hosts:
        - {{ (index .Values.ingress.hosts 0).host }}
      secretName: {{ (index .Values.ingress.tls 0).secretName }}