apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    - host: argocd.hometsd.me
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
  tls:
    - hosts:
        - argocd.hometsd.me
      secretName: argocd.hometsd.me-tls