apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ing
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - {{ .Values.domain }}
      secretName: argocd-hometsd-me-tls
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: argocd-web
                port:
                  number: 443