replicaCount: 1

image:
  repository: registry.gitlab.com/dotsd/tsd-quotation-api
  pullPolicy: Always
  tag: "latest"

imagePullSecrets : [gitlab-secert]
service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.quotatoin.tsdrancher.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - api.quotatoin.tsdrancher.com
      secretName: api-quotatoin-tsdrancher-com-tls
envSecrets:
  name: env-quotation-api
