apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: accvilage-web
spec:
  destination:
    name: ''
    namespace: accvilage-web
    server: 'https://kubernetes.default.svc'
  source:
    path: applications/accvillage-web
    repoURL: 'https://github.com/Domie94/k8s-01.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
