apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/Domie94/k8s-01.git'
        revision: main
        directories:
          - path: 'applications/rabbitmq'
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Domie94/k8s-01.git'
        targetRevision: main
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: rabbitmq
      syncPolicy:
        automated:
          prune: true # Enables automatic pruning of resources not defined in Git
          selfHeal: true # Enables automatic self-healing to keep the application in sync
        syncOptions:
          - CreateNamespace=true # Ensures the namespace is created if it doesn’t already exist
