apiVersion: v2
name: hashicorp-vault
description: A Helm chart for deploying HashiCorp Vault on Kubernetes
type: application
version: 0.1.0
appVersion: "1.18.1"

dependencies:
  - name: vault
    version: "0.29.0"
    repository: "https://helm.releases.hashicorp.com"
