apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "accvillage-web.fullname" . }}
  labels:
    app: {{ include "accvillage-web.name" . }}
  annotations:
    argocd-image-updater.argoproj.io/image-list: "{{ .Values.image.repository }}"
    argocd-image-updater.argoproj.io/{{ .Values.image.repository }}.update-strategy: latest
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "accvillage-web.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "accvillage-web.name" . }}
    spec:
      containers:
        - name: accvillage-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: {{ .Values.envSecrets.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets | first }}