apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapi.fullname" . }}
  labels:
    app: {{ include "webapi.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3001
  selector:
    app: {{ include "webapi.name" . }}