apiVersion: v1
kind: ConfigMap
metadata:
  name: taxris-nginx-config
data:
  nginx.conf: |
    server {
        listen 80;
        server_name taxris.hometsd.me;

        location / {
            proxy_pass http://tws.mof.gov.la:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
