apiVersion: v1
kind: ConfigMap
metadata:
  name: forward-proxy-config
data:
  nginx.conf: |
    server {
        listen 80;
        location /mediate/TaxRIS/createPfmFromCRSDtl/SndCrs {
            proxy_pass http://tws.mof.gov.la:8080/mediate/TaxRIS/createPfmFromCRSDtl/SndCrs; # URL ต้นทาง
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
