apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ing
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - taxris.hometsd.me
      secretName: argocd-hometsd-me-tls
  rules:
    - host: taxris.hometsd.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taxris-nginx-service
                port:
                  name: 80