apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taxris-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  rules:
  - host: taxris.hometsd.me
    http:
      paths:
      - path: /mediate/TaxRIS/createPfmFromCRSDtl/SndCrs
        pathType: Prefix
        backend:
          service:
            name: taxris-nginx-service
            port:
              number: 80
