apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forward-proxy-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  
spec:
  rules:
  - host: tsdtax.hometsd.me  
    http:
      paths:
      - path: /mediate/TaxRIS/createPfmFromCRSDtl/SndCrs
        pathType: Prefix  
        backend:
          service:
            name: forward-proxy-service
            port:
              number: 80
