apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auto-deploy
  namespace: argocd
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/Domie94/k8s-01.git
    path: 'applications'

  # Destination cluster and namespace to deploy the application
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
