apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlserver-pv
  labels:
    app: sqlserver
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/sqlserver # Replace with a directory on your node
