apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-manual
  labels:
    app: sqlserver
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/sqlserver