apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mssql-pv
  labels:
    app: {{ .Chart.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  hostPath:
    path: /mnt/data/{{ .Release.Name }}-mssql
