apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mssql-pv
  labels:
    app: {{ .Chart.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "manual"
  hostPath:
    path: /mnt/data/{{ .Release.Name }}-mssql # Replace this path with a directory on the node
