apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mssql
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: 1433
      targetPort: 1433
      protocol: TCP
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}
