apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mssql
  labels:
    app: {{ .Chart.Name }}
spec:
  serviceName: {{ .Release.Name }}-mssql
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: mssql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: tcpsql
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.key }}
          securityContext:
            runAsUser: 10001
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: mssql-storage
              mountPath: /var/opt/mssql
  volumeClaimTemplates:
    - metadata:
        name: mssql-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
