
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: argocd.hometsd.me
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - argocd.hometsd.me
      secretName: argocd.hometsd.me-tls
