replicaCount: 1

image:
  repository: mcr.microsoft.com/mssql/server
  tag: "2022-latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1433

persistence:
  storageClass: "manual"
  size: 30Gi                      # Storage size for PVC
