replicaCount: 1

image:
  repository: mcr.microsoft.com/mssql/server
  tag: "2022-latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1433

persistence:
  storageClass: "do-block-storage"
  size: 10Gi

secret:
  name: mssql-sa-password-secret  # Ensure this matches the name of your Kubernetes secret
  key: MSSQL_SA_PASSWORD          # Key inside the secret
