replicaCount: 1

image:
  repository: mcr.microsoft.com/mssql/server
  tag: "2022-latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1433

persistence:
  storageClass: "do-block-storage" # Use DigitalOcean's StorageClass
  size: 30Gi                      # Define storage size for the PersistentVolumeClaim

secret:
  name: mssql-sa-password-secret  # Kubernetes Secret name
  key: MSSQL_SA_PASSWORD          # Key inside the Secret
