apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tsd-taxris-upload.fullname" . }}
  labels:
    app: {{ include "tsd-taxris-upload.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "tsd-taxris-upload.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "tsd-taxris-upload.name" . }}
    spec:
      containers:
        - name: tsd-taxris-upload
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets | first }}