apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vault-config
  labels:
    app: {{ .Chart.Name }}
data:
  config.hcl: |
    listener "tcp" {
      address = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_disable = {{ .Values.tls.enabled | ternary "false" "true" }}
    }
    storage "file" {
      path = "/vault/data"
    }
