apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vault
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:{{ .Chart.AppVersion }}
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_API_ADDR
              value: http://0.0.0.0:8200
            - name: VAULT_CLUSTER_ADDR
              value: https://0.0.0.0:8201
