apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-vault-pvc
  labels:
    app: {{ .Chart.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.dataStorage.size }}
  storageClassName: {{ .Values.server.dataStorage.storageClass }}
