apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vault
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8200
      targetPort: 8200
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
