apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "accvillage-api.fullname" . }}
  labels:
    app: {{ include "accvillage-api.name" . }}
  annotations:
{{- if .Values.vault.enabled }}
{{ toYaml .Values.vault.annotations | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "accvillage-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "accvillage-api.name" . }}
    spec:
      containers:
        - name: accvillage-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker/config.json
              subPath: config.json
      volumes:
        - name: docker-config
          emptyDir: {}
      # imagePullSecrets:
      #   - name: {{ .Values.imagePullSecrets | first }}