apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootsrap-app                # The name of the Argo CD application
  namespace: argocd                    # Namespace where Argo CD is installed
spec:
  project: default                     # Argo CD project to use (default or custom project)
  source:
    repoURL: 'https://github.com/Domie94/k8s-01.git'   # Git repository URL containing the Helm chart
    targetRevision: main                        # Branch, tag, or commit SHA to deploy (e.g., "main")
    path: applicatins                        # Path to the Helm chart within the Git repo
    helm:
      valueFiles:                             # Optional: specify custom values files
        - values.yaml                         # Helm values file within the chart
  destination:
    server: 'https://kubernetes.default.svc'  # Kubernetes API server (default for in-cluster deployment)
    namespace: bootsrap-app               # Namespace in the cluster for the application
  syncPolicy:
    automated:                                # Optional: enable automated sync
      prune: true                             # Remove resources no longer in the Git repo
      selfHeal: true                          # Auto-sync resources that drift from the desired state
    syncOptions:
      - CreateNamespace=true                  # Create the namespace if it doesn’t exist
