replicaCount: 1

image:
  repository: tsdadmin/villageaccountingfontend
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: hub-docker

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: hometsd.me
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - hometsd.me
      secretName: hometsd-me-tls