# Default values for tsd-quotation-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: registry.gitlab.com/dotsd/tsd-quotation-api
  # This sets the pull policy for images.
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.3"

# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets:
  - name: gitlab-secert
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: 
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 3000

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: "nginx"
  annotations: 
    # Ingress class
    kubernetes.io/ingress.class: nginx

    # Cert-Manager สำหรับ SSL
    cert-manager.io/cluster-issuer: "letsencrypt-prod"   # ระบุ ClusterIssuer ของ Cert-Manager
    kubernetes.io/tls-acme: "true"                      # ใช้ ACME protocol สำหรับสร้างใบรับรอง TLS

    # Proxy และ Body Size
    nginx.ingress.kubernetes.io/proxy-body-size: "50m" # กำหนดขนาดสูงสุดของข้อมูลที่ Ingress จะรับได้
    nginx.ingress.kubernetes.io/rewrite-target: /      # แปลงเส้นทางไปยังรากของ backend

    # Rate Limiting (ป้องกัน DDoS)
    nginx.ingress.kubernetes.io/limit-connections: "20"                # จำกัดการเชื่อมต่อพร้อมกันต่อ IP
    nginx.ingress.kubernetes.io/limit-rps: "10"                       # จำกัด requests ต่อวินาทีต่อ IP
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "2"           # อนุญาต burst requests

    # CORS (เปิดการใช้งานข้ามโดเมน)
    nginx.ingress.kubernetes.io/enable-cors: "true"                   # เปิดการใช้งาน CORS
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"                # อนุญาตทุกโดเมน (*ควรปรับสำหรับการใช้งานจริง)
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS" # HTTP Methods ที่อนุญาต
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type"    # HTTP Headers ที่อนุญาต
    nginx.ingress.kubernetes.io/cors-max-age: "3600"                  # อายุของข้อมูล CORS ใน cache

    # Buffering และ Timeouts (ปรับประสิทธิภาพ)
    nginx.ingress.kubernetes.io/proxy-buffering: "on"                 # เปิดการบัฟเฟอร์ข้อมูล
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"             # จำนวนบัฟเฟอร์
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"              # ขนาดของแต่ละบัฟเฟอร์
    nginx.ingress.kubernetes.io/proxy-read-timeout: "10"             # เวลารออ่านข้อมูลจาก backend (วินาที)
    nginx.ingress.kubernetes.io/proxy-send-timeout: "10"             # เวลารอส่งข้อมูลไป backend (วินาที)

    # SSL (เพิ่มความปลอดภัย)
    nginx.ingress.kubernetes.io/ssl-redirect: "true"                  # บังคับเปลี่ยน HTTP เป็น HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"            # บังคับใช้งาน SSL ตลอดเวลา
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"                # ตรวจสอบ SSL ระหว่าง Ingress และ backend

    # Logging (สำหรับ Debugging)
    nginx.ingress.kubernetes.io/enable-access-log: "true"             # เปิด Access Logs
    nginx.ingress.kubernetes.io/enable-error-log: "true"              # เปิด Error Logs

    

  hosts:
    - host: api.quotation.tsdrancher.com
      paths:
        - path: /
          pathType: Prefix
  tls: 
   - secretName: api-quotation-tsdrancher-com-tls
     hosts:
       - api.quotation.tsdrancher.com

resources:

  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 120
  timeoutSeconds: 5
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 120
  timeoutSeconds: 2
  failureThreshold: 3

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
envSecrets:
  name: env-quotation-api
