postgresql:
  auth:
    existingSecret: new-password-secret
    
  primary:
    persistence:
      size: 20Gi
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenScaled: Retain
      whenDeleted: Retain
