postgresql:
  architecture: "replication"
  
  auth:
    user: "dev"
    postgresPassword: "bmV3R2VuZXJhdGVkUGFzc3dvcmQxMjM=" 
    password: "bmV3VXNlclBhc3N3b3JkMTIz" 
    replicationPassword: "bmV3UmVwbGljYXRpb25QYXNzd29yZDEyMw=="
  passwordUpdateJob:
    enabled: true

pgadmin4:
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: pgadmin.tsdrancher.com
        paths:
          - path: /
            pathType: Prefix
    tls: 
      - secretName: pgadmin-tsdrancher-tls
        hosts:
          - pgadmin.tsdrancher.com
  secretKeys:
    pgadminPasswordKey: pgadmin-password
  env:
    email: chart@d2323omain.com
    password: SuperSecret2323